---
title: "Week 03 Assignment 02_datasets"
author: "Jailee Foster"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    citation_package: natbib
    latex_engine: pdflatex
    template: /Users/jaileefoster/Desktop/stat419/_git_/WSU_STATS419_FALL2020/latex-templates/homework.tex
    fig_caption: true
    number_section: true
  html_document:
    df_print: paged
email: jailee.foster@wsu.edu
instructor: Monte J. Shaffer
course-short: STATS419
course: STATS 419 Survey of Multivariate Analysis
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r one, message=FALSE}
library(devtools); # devtools is required for function source_url() to work
my.source = 'github';
github.path.instructor = "https://raw.githubusercontent.com/MonteShaffer/WSU_STATS419_FALL2020/";
github.path = "https://raw.githubusercontent.com/jaileefoster/WSU_STATS419_FALL2020/";
source_url(paste0(github.path.instructor, "master/functions/libraries.R"));
source_url("https://raw.githubusercontent.com/MonteShaffer/WSU_STATS419_FALL2020/master/functions/functions-imdb.R"); 
```

Malcolm Gladwell\footnote{asdf} talks about outliers \citep{Gladwell:2008}.

\citet{Gladwell:2008} talks about outliers.

We would like to thank \citet{Rmarkdown:Latex:Templates} for help with our Latex template. 
